"""empty message

Revision ID: b8d75a80fba0
Revises: 8936f23d59f3
Create Date: 2020-07-07 14:47:43.759720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8d75a80fba0'
down_revision = '8936f23d59f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('markdown', sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'markdown')
    # ### end Alembic commands ###
